/**
 * SF Bay Ferry Routes + Shipping Lanes — Safety Overlay
 *
 * All geometry is routed to stay on navigable water. Coordinates
 * pass scripts/validate-ferry-routes.ts against the OSM coastline
 * polygons in data/geo/sf-bay-coastline.json. They were either
 * copied from validated verified-routes.ts paths or generated by
 * scripts/fix-ferry-routes.ts, which inserts perpendicular
 * waypoints until every segment stays in water.
 *
 * Validation:
 *   npx tsx scripts/validate-ferry-routes.ts
 *   npx tsx scripts/fix-ferry-routes.ts       # regenerates /tmp/ferry-routes-fixed.json
 *
 * Sources:
 *   - Golden Gate Ferry (Sausalito / Larkspur schedules + track maps)
 *   - SF Bay Ferry / WETA (Oakland / Alameda / Richmond / Vallejo)
 *   - Blue & Gold Fleet (Tiburon / Angel Island)
 *   - Alcatraz City Cruises
 *   - NOAA Chart 18649 + USCG COTP San Francisco Bay TSS
 *
 * Coordinates are [lng, lat] (GeoJSON order). Ferries travel 20-34 kts
 * and cannot stop quickly — kayaks and SUPs are nearly invisible to
 * ferry crews, especially in fog. The overlay is advisory, not a
 * real-time AIS feed.
 */

export interface FerryRoute {
  name: string;
  operator: string;
  coordinates: [number, number][];
  speedKts: number;
  frequency: string;
}

export const ferryRoutes: FerryRoute[] = [
  {
    name: 'Sausalito Ferry',
    operator: 'Golden Gate Ferry',
    // SF Ferry Building → Central Bay → around east side of Angel Is
    // → Raccoon Strait → Richardson Bay → Sausalito.
    coordinates: [
      [-122.3935, 37.7955],
      [-122.4000, 37.8200],
      [-122.4100, 37.8300],
      [-122.4300, 37.8400],
      [-122.4486, 37.8578],
      [-122.4384, 37.8720],
      [-122.4480, 37.8735],
      [-122.4510, 37.8713],
      [-122.4570, 37.8724],
      [-122.4538, 37.8661],
      [-122.4650, 37.8550],
      [-122.4783, 37.8602],
      [-122.4850, 37.8600],
    ],
    speedKts: 25,
    frequency: 'Every 30-60 min',
  },
  {
    name: 'Larkspur Ferry',
    operator: 'Golden Gate Ferry',
    // SF Ferry Building → Central Bay → east of Angel Island →
    // San Pablo Strait → approach to Corte Madera Channel. The final
    // dredged channel is too narrow to render cleanly, so the line
    // terminates in open water NE of the actual dock.
    coordinates: [
      [-122.3935, 37.7955],
      [-122.4000, 37.8200],
      [-122.4100, 37.8300],
      [-122.4000, 37.8700],
      [-122.3900, 37.9000],
      [-122.4100, 37.9300],
      [-122.4500, 37.9400],
      [-122.4800, 37.9499],
    ],
    speedKts: 30,
    frequency: 'Every 30-60 min (commute)',
  },
  {
    name: 'Oakland/Alameda Ferry',
    operator: 'SF Bay Ferry (WETA)',
    // SF Ferry Building → Oakland Estuary entrance → Jack London Sq.
    // Path mirrors validated sfm_jls waypoints.
    coordinates: [
      [-122.3935, 37.7955],
      [-122.3685, 37.8065],
      [-122.3400, 37.8100],
      [-122.3434, 37.8055],
      [-122.3400, 37.8000],
      [-122.3200, 37.7970],
      [-122.3100, 37.7930],
      [-122.2780, 37.7940],
    ],
    speedKts: 28,
    frequency: 'Every 30 min',
  },
  {
    name: 'Alameda Harbor Bay Ferry',
    operator: 'SF Bay Ferry (WETA)',
    // SF Ferry Building → south of YBI / Bay Bridge → SE across Bay
    // → Harbor Bay Isle terminal.
    coordinates: [
      [-122.3935, 37.7955],
      [-122.3700, 37.7820],
      [-122.3300, 37.7600],
      [-122.2850, 37.7400],
      [-122.2544, 37.7288],
    ],
    speedKts: 28,
    frequency: 'Commute hours only',
  },
  {
    name: 'Richmond Ferry',
    operator: 'SF Bay Ferry (WETA)',
    // SF Ferry Building → east of Angel Is → N to Richmond ferry terminal.
    coordinates: [
      [-122.3935, 37.7955],
      [-122.4000, 37.8200],
      [-122.4100, 37.8300],
      [-122.4000, 37.8700],
      [-122.3900, 37.9000],
      [-122.3710, 37.8994],
      [-122.3677, 37.9003],
      [-122.3544, 37.9100],
    ],
    speedKts: 30,
    frequency: 'Every 60 min',
  },
  {
    name: 'Vallejo Ferry',
    operator: 'SF Bay Ferry (WETA)',
    // SF Ferry Building → Central Bay → San Pablo Strait → east-side
    // San Pablo Bay → Carquinez Strait → Mare Island Strait S approach.
    // Final Mare Island Strait channel is very narrow, so we terminate
    // in open water SE of the Vallejo dock.
    coordinates: [
      [-122.3935, 37.7955],
      [-122.4000, 37.8200],
      [-122.4100, 37.8300],
      [-122.4000, 37.8700],
      [-122.3900, 37.9000],
      [-122.4100, 37.9300],
      [-122.4500, 37.9432],
      [-122.4500, 37.9568],
      [-122.4100, 37.9900],
      [-122.4000, 38.0200],
      [-122.3700, 38.0500],
      [-122.3200, 38.0600],
      [-122.2800, 38.0620],
      [-122.2633, 38.0679],
    ],
    speedKts: 34,
    frequency: 'Every 60 min',
  },
  {
    name: 'Angel Island Ferry',
    operator: 'Blue & Gold Fleet',
    // SF Pier 41 → W past Alcatraz → around E side of Angel Island
    // → approach Ayala Cove from the NE via Raccoon Strait.
    // Path adapted from validated sfm_ang waypoints.
    coordinates: [
      [-122.4094, 37.8095],
      [-122.3968, 37.8090],
      [-122.4300, 37.8400],
      [-122.4550, 37.8550],
      [-122.4480, 37.8700],
      [-122.4383, 37.8690],
      [-122.4346, 37.8673],
    ],
    speedKts: 20,
    frequency: 'Seasonal, 4-6 trips/day',
  },
  {
    name: 'Tiburon Ferry',
    operator: 'Blue & Gold Fleet',
    // SF Pier 41 → Central Bay → approach Raccoon Strait from the SW
    // → Tiburon terminal.
    coordinates: [
      [-122.4094, 37.8095],
      [-122.4062, 37.8103],
      [-122.3968, 37.8090],
      [-122.4100, 37.8300],
      [-122.4300, 37.8400],
      [-122.4146, 37.8560],
      [-122.4150, 37.8700],
      [-122.4299, 37.8728],
      [-122.4351, 37.8713],
      [-122.4518, 37.8715],
      [-122.4552, 37.8726],
    ],
    speedKts: 20,
    frequency: 'Seasonal',
  },
  {
    name: 'Alcatraz Ferry',
    operator: 'Alcatraz City Cruises',
    // SF Pier 33 → Alcatraz Island landing.
    coordinates: [
      [-122.4095, 37.8110],
      [-122.4198, 37.8268],
      [-122.4220, 37.8280],
    ],
    speedKts: 15,
    frequency: 'Every 30 min (high season)',
  },
];

// ──────────────────────────────────────────────────────────────────────
// Major shipping lanes inside SF Bay
// ──────────────────────────────────────────────────────────────────────
//
// Inside the Bay, commercial traffic follows well-known channels:
//
//   1. San Francisco Bar → Golden Gate → Port of Oakland
//      (container ships to Oakland Outer/Inner Harbor)
//   2. Golden Gate → Richmond Long Wharf
//      (Chevron refinery tankers)
//   3. Golden Gate → San Pablo Bay → Carquinez Strait → Suisun Bay
//      (refinery tankers to Martinez/Benicia/Rodeo, river barges)
//
// These lanes carry vessels >600 ft LOA that cannot change course
// quickly. Small craft must yield and avoid crossing during transits.

export interface ShippingLane {
  id: string;
  name: string;
  description: string;
  coordinates: [number, number][];
  color: string;
}

export const shippingLanes: ShippingLane[] = [
  {
    id: 'gg_oakland',
    name: 'Oakland Deep Water Channel',
    description:
      'Container ships from SF Bar to Port of Oakland. ~600–1000 ft LOA, 12–16 kt transit speed.',
    // Simplified endpoint at the outer harbor — the dredged channel
    // inside the Inner Harbor is too narrow to render reliably.
    coordinates: [
      [-122.6500, 37.7850],
      [-122.5600, 37.8000],
      [-122.5000, 37.8150],
      [-122.4783, 37.8199],
      [-122.4500, 37.8220],
      [-122.4200, 37.8250],
      [-122.4000, 37.8250],
      [-122.3800, 37.8100],
      [-122.3600, 37.8050],
      [-122.3450, 37.8080],
      [-122.3350, 37.8130],
    ],
    color: '#f59e0b',
  },
  {
    id: 'gg_richmond',
    name: 'Richmond Long Wharf Channel',
    description:
      'Chevron refinery tankers to Richmond Long Wharf. Transits San Pablo Strait.',
    coordinates: [
      [-122.5000, 37.8150],
      [-122.4783, 37.8199],
      [-122.4500, 37.8220],
      [-122.4200, 37.8400],
      [-122.4150, 37.8700],
      [-122.4150, 37.9000],
      [-122.4200, 37.9200],
      [-122.4100, 37.9260],
      [-122.4040, 37.9260],
    ],
    color: '#f59e0b',
  },
  {
    id: 'gg_carquinez',
    name: 'Carquinez / Suisun Tanker Lane',
    description:
      'Refinery tankers and river barges transiting to Martinez, Benicia, Rodeo, and the Delta.',
    coordinates: [
      [-122.5000, 37.8150],
      [-122.4783, 37.8199],
      [-122.4500, 37.8220],
      [-122.4200, 37.8400],
      [-122.4150, 37.8700],
      [-122.4150, 37.9100],
      [-122.4131, 37.9442],
      [-122.4569, 37.9552],
      [-122.4100, 37.9900],
      [-122.4000, 38.0200],
      [-122.3700, 38.0500],
      [-122.3200, 38.0600],
      [-122.2800, 38.0620],
      [-122.2300, 38.0600],
      [-122.2035, 38.0556],
      [-122.1800, 38.0500],
      [-122.1632, 38.0434],
      [-122.1500, 38.0400],
    ],
    color: '#f59e0b',
  },
];

/**
 * Generate GeoJSON for ferry routes + shipping lanes overlay.
 */
export function ferryRoutesGeoJSON() {
  const features = [
    // Ferry routes
    ...ferryRoutes.map(route => ({
      type: 'Feature' as const,
      geometry: {
        type: 'LineString' as const,
        coordinates: route.coordinates,
      },
      properties: {
        name: route.name,
        operator: route.operator,
        speedKts: route.speedKts,
        frequency: route.frequency,
        type: 'ferry',
        color: '#ef4444', // danger-red — ferries are hazardous to small craft
        opacity: 0.6,
        lineWidth: 2,
        dashArray: [4, 4],
      },
    })),
    // Shipping lanes
    ...shippingLanes.map(lane => ({
      type: 'Feature' as const,
      geometry: {
        type: 'LineString' as const,
        coordinates: lane.coordinates,
      },
      properties: {
        name: lane.name,
        operator: 'Commercial shipping',
        description: lane.description,
        speedKts: 14,
        frequency: 'Continuous',
        type: 'shipping',
        color: lane.color,
        opacity: 0.45,
        lineWidth: 8,
        dashArray: [0, 0],
      },
    })),
  ];

  return {
    type: 'FeatureCollection' as const,
    features,
  };
}

/**
 * Back-compat alias — the original file exported `shippingChannel`
 * as the Oakland lane. Preserve that export so nothing breaks.
 */
export const shippingChannel = shippingLanes[0].coordinates;
